Repository MrKrishnaAgarwal/Hello-World, pull requests merged in 2022-10, with the labels that each got.

#2 Add Perl and SQL
  main.pl
  main.sql
Labels: enhancement, good first issue

#6 Added Hello World Using EJS and Express.
  .gitignore
  EJS/Hello.js
  EJS/views/Hello.ejs
Labels: hacktoberfest-accepted

#7 Add x86 Assembly and Brainf*ck to the list.
  main.asm
  main.bf
Labels: hacktoberfest-accepted

#10 add reactjs
  main_react.js
Labels: hacktoberfest-accepted

#13 add bhai lang
  README.md
  main_bhai_lang.bhai.txt
Labels: hacktoberfest-accepted

#14 add node js
  README.md
  main_node.js
Labels: hacktoberfest-accepted

#20 Create main_angular.js
  main_angular.js
Labels: good first issue, hacktoberfest-accepted

#18 Hello,World in Fortan
  main.f90
Labels: good first issue, hacktoberfest-accepted

#17 Add groovy
  README.md
  main.groovy
Labels: good first issue, hacktoberfest-accepted

#23 add carbon
  main.carbon
Labels: hacktoberfest-accepted

#24 Coffee Script
  main.coffee
Labels: hacktoberfest-accepted

#26 Pascal
  main.pas
Labels: hacktoberfest-accepted

#21 added visual basic
  main.vb
Labels: invalid
